#!/bin/bash

profiles=($(cat ~/.aws/config | grep -o '\[[^]]*\]' | sed 's/^\[profile \(.*\)\]$/\1/g'))

for index in ${!profiles[@]}; do
    echo "[$index]: ${profiles[$index]}"
done

echo ""
read -p "Enter index to set profile: " index

export AWS_PROFILE=${profiles[$index]}
